### ISSUE TITLE
Chart

### ISSUE THREAD

**Issue by rslruiz** [keane-sulit/sl3AquamanProject#1]
Prepare a hierarchy chart <https://en.wikibooks.org/wiki/Programming_Fundamentals/Hierarchy_or_Structure_Chart>.

**Comment by keane-sulit** [comment]
Just saw this comment, sir. We're currently doing it. We will commit it as soon as possible.

**Comment by keane-sulit** [comment]
Done. See `hierarchy_chart.png`.
